#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/IK1.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jama.jar:$APPDIR/lib/jama.jar:$APPDIR/lib/jama.jar:$APPDIR/lib/jama.jar" IK1
