    <td class="main_content_box">

<table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="left_content">

<i>For coding, like art, should be admired on its own merits, and, like nature, should be investigated for its own wonders.</i>

	</td>
        <td class="body_content">

<strong>Examples</strong> <br />
          <br />

<p>
	<b>Developing C++ OpenGL applications with Eclipse and Linux</b>
	<br>I prefer to use Eclipse for my Java and C++ development, and naturally I run Linux.
	It took a couple of tries to get everything installed and working, so let me share my methods.
	<br><i>Operating System:</i> Ubuntu 7.10 Linux
	<br><i>Eclipse:</i> Eclipse Classic v.3.3.x
	<br><i>Eclipse Plugins Installed:</i> Subclipse, CDT 
	<br><i>Debian Packages Installed:</i> 	
	<blockquote>
		Setting up x11proto-core-dev (7.0.10-2) ...
		Setting up libice-dev (2:1.0.3-3) ...
		Setting up libsm-dev (2:1.0.3-1) ...
		Setting up libxau-dev (1:1.0.3-2) ...
		Setting up libxdmcp-dev (1:1.0.2-2) ...
		Setting up x11proto-input-dev (1.4.2-1) ...
		Setting up x11proto-kb-dev (1.0.3-2ubuntu1) ...
		Setting up xtrans-dev (1.0.3-2) ...
		Setting up libx11-dev (2:1.1.1-1ubuntu4) ...
		Setting up x11proto-xext-dev (7.0.2-5ubuntu1) ...
		Setting up libxext-dev (2:1.0.3-2build1) ...
		Setting up libxt-dev (1:1.0.5-3) ...
		Setting up mesa-common-dev (7.0.1-1ubuntu3) ...
		Setting up libgl1-mesa-dev (7.0.1-1ubuntu3) ...
		Setting up xlibmesa-gl-dev (1:7.2-5ubuntu13) ...
		Setting up libglu1-mesa-dev (7.0.1-1ubuntu3) ...
		Setting up freeglut3-dev (2.4.0-5.1ubuntu1) ...
		Setting up freeglut3-dbg (2.4.0-5.1ubuntu1) ...
		Setting up libgl1-mesa-dri-dbg (7.0.1-1ubuntu3) ...
		Setting up libgl1-mesa-glx-dbg (7.0.1-1ubuntu3) ...
		Setting up mesademos (6.2.1-1) ...
	</blockquote>
	<br><a href="http://www.oreillynet.com/pub/a/network/2000/06/23/magazine/opengl_build.html?page=2">This link</a> helped me get up and running!
</p>

<p>
<b>C++ Basics</b>
<br>A simple <a href="examples/swap.cpp">swap</a> example to demonstrate pointer swapping.
<br>An example of <a href="examples/obj.cpp">deep versus shallow copying</a> of objects.
</p>

	 </td>
      </tr>
    </table>
